default_context:
  project_name: 'ElderBrain'
  project_slug: 'elderbrain'
  domain_main: 'elderbrain.com'
  domain_staging: 'stag.elderbrain.com'
  docker_swarm_stack_name_main: 'elderbrain-com'
  docker_swarm_stack_name_staging: 'stag-elderbrain-com'
  secret_key: '5284326591a03133cbda6f5d7614f4f313fea522f4b98ef11ea6e72fd8017877'
  first_superuser: 'admin@elderbrain.com'
  first_superuser_password: 'd184fd0d12b5768893a16cc32f8c4677962ef2ec7d1c246de3d547634f054335'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.elderbrain.com", "https://stag.elderbrain.com", "https://elderbrain.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@elderbrain.com'
  postgres_password: 'dac8b83db7f54c815ed5fd2fc7a1b71362d7b0094f51efebd275761c2bbb1cd2'
  pgadmin_default_user: 'admin@elderbrain.com'
  pgadmin_default_user_password: 'd184fd0d12b5768893a16cc32f8c4677962ef2ec7d1c246de3d547634f054335'
  traefik_constraint_tag: 'elderbrain.com'
  traefik_constraint_tag_staging: 'stag.elderbrain.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:d184fd0d12b5768893a16cc32f8c4677962ef2ec7d1c246de3d547634f054335'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
