"""Add Achievement model

Revision ID: 76861b8340fd
Revises: d4867f3a4c0a
Create Date: 2020-11-20 07:41:53.629452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76861b8340fd'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('achieved_by_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achieved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_description'), 'achievement', ['description'], unique=False)
    op.create_index(op.f('ix_achievement_id'), 'achievement', ['id'], unique=False)
    op.create_index(op.f('ix_achievement_public'), 'achievement', ['public'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_achievement_public'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_id'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_description'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
